services:
  mongodb:
    image: mongo:8
    container_name: toxicai-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: toxicai-app
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://mongodb:27017
      MONGODB_DB: toxic_comment_db
      ENVIRONMENT: production
    ports:
      - "8000:8000"

volumes:
  mongo_data:
